/**
 * Delve Client SDK
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.8
 * Contact: support@relational.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RaiDbSdk);
  }
}(this, function(expect, RaiDbSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RaiDbSdk.CSVFileSyntax();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CSVFileSyntax', function() {
    it('should create an instance of CSVFileSyntax', function() {
      // uncomment below and update the code to test CSVFileSyntax
      //var instane = new RaiDbSdk.CSVFileSyntax();
      //expect(instance).to.be.a(RaiDbSdk.CSVFileSyntax);
    });

    it('should have the property datarow (base name: "datarow")', function() {
      // uncomment below and update the code to test the property datarow
      //var instane = new RaiDbSdk.CSVFileSyntax();
      //expect(instance).to.be();
    });

    it('should have the property delim (base name: "delim")', function() {
      // uncomment below and update the code to test the property delim
      //var instane = new RaiDbSdk.CSVFileSyntax();
      //expect(instance).to.be();
    });

    it('should have the property escapechar (base name: "escapechar")', function() {
      // uncomment below and update the code to test the property escapechar
      //var instane = new RaiDbSdk.CSVFileSyntax();
      //expect(instance).to.be();
    });

    it('should have the property header (base name: "header")', function() {
      // uncomment below and update the code to test the property header
      //var instane = new RaiDbSdk.CSVFileSyntax();
      //expect(instance).to.be();
    });

    it('should have the property headerRow (base name: "header_row")', function() {
      // uncomment below and update the code to test the property headerRow
      //var instane = new RaiDbSdk.CSVFileSyntax();
      //expect(instance).to.be();
    });

    it('should have the property ignorerepeated (base name: "ignorerepeated")', function() {
      // uncomment below and update the code to test the property ignorerepeated
      //var instane = new RaiDbSdk.CSVFileSyntax();
      //expect(instance).to.be();
    });

    it('should have the property missingstrings (base name: "missingstrings")', function() {
      // uncomment below and update the code to test the property missingstrings
      //var instane = new RaiDbSdk.CSVFileSyntax();
      //expect(instance).to.be();
    });

    it('should have the property normalizenames (base name: "normalizenames")', function() {
      // uncomment below and update the code to test the property normalizenames
      //var instane = new RaiDbSdk.CSVFileSyntax();
      //expect(instance).to.be();
    });

    it('should have the property quotechar (base name: "quotechar")', function() {
      // uncomment below and update the code to test the property quotechar
      //var instane = new RaiDbSdk.CSVFileSyntax();
      //expect(instance).to.be();
    });

  });

}));
